import Head from "next/head";
import Header from "@/components/Header";
import { useTranslation } from "react-i18next";
import { useState, useEffect } from "react";
import LoaderPage from "@/components/LoaderPage";
import ErrorOnLoadingThePage from "@/components/ErrorOnLoadingThePage";
import { getAnimationSettings, getInitialStateForElementBeforeAnimation, getUserInfo, handleSelectUserLanguage } from "../../../public/global_functions/popular";
import Footer from "@/components/Footer";
import { motion } from "motion/react";

export default function PolicesTermsAndConditions() {

    const [isLoadingPage, setIsLoadingPage] = useState(true);

    const [errorMsgOnLoadingThePage, setErrorMsgOnLoadingThePage] = useState("");

    const { t, i18n } = useTranslation();

    useEffect(() => {
        const userLanguage = localStorage.getItem(process.env.userlanguageFieldNameInLocalStorage);
        handleSelectUserLanguage(userLanguage === "ar" || userLanguage === "en" || userLanguage === "tr" || userLanguage === "de" ? userLanguage : "en", i18n.changeLanguage);
    }, []);

    useEffect(() => {
        const userToken = localStorage.getItem(process.env.userTokenNameInLocalStorage);
        if (userToken) {
            getUserInfo()
                .then((result) => {
                    if (result.error) {
                        localStorage.removeItem(process.env.userTokenNameInLocalStorage);
                    }
                    setIsLoadingPage(false);
                })
                .catch((err) => {
                    if (err?.response?.status === 401) {
                        localStorage.removeItem(process.env.userTokenNameInLocalStorage);
                        setIsLoadingPage(false);
                    }
                    else {
                        setIsLoadingPage(false);
                        setErrorMsgOnLoadingThePage(err?.message === "Network Error" ? "Network Error" : "Sorry, Something Went Wrong, Please Try Again !");
                    }
                });
        } else {
            setIsLoadingPage(false);
        }
    }, []);

    return (
        <div className="privacy-policy-and-conditions caption-page page pt-5">
            <Head>
                <title>{t(process.env.storeName)} - {t("Polices Terms And Conditions")}</title>
            </Head>
            {!isLoadingPage && !errorMsgOnLoadingThePage && <>
                <Header />
                <div className="page-content text-white ps-4 pe-4 pb-5">
                    <div className="container-fluid">
                        <motion.h1
                            className="welcome-msg mb-5 border-bottom border-2 pb-3 w-fit mx-auto"
                            initial={getInitialStateForElementBeforeAnimation()}
                            whileInView={getAnimationSettings}
                        >{t("Polices-Terms & Conditions")}</motion.h1>
                        <div className="content">
                            <motion.h2
                                className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2"
                                initial={getInitialStateForElementBeforeAnimation()}
                                whileInView={getAnimationSettings}
                            >{t("Introduction")}</motion.h2>
                            <motion.p
                                className="mb-5"
                                initial={getInitialStateForElementBeforeAnimation()}
                                whileInView={getAnimationSettings}
                            >{t("This privacy notice defines how Ubuyblues or its owner or operator of this website collects and processes your personal data for the promotion, execution, and provision of Ubuyblues services. By visiting this website, submitting your personal data, or accessing Ubuyblues services or purchasing them, you expressly agree to comply with the terms and conditions of this privacy notice. If you do not agree, please refrain from using or accessing this website or any Ubuyblues services .")}</motion.p>
                            <motion.h2
                                className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2"
                                initial={getInitialStateForElementBeforeAnimation()}
                                whileInView={getAnimationSettings}
                            >{t("Definitions")}</motion.h2>
                            <ul>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The term 'subsidiary company' refers to any individual or entity, another individual or entity that, directly or indirectly, through one or more intermediaries, controls or is controlled by or is under common control with this individual or entity")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Products and Services' refers to the products and services offered by Ubuyblues online on any website and/or services and call centers, including but not limited to Ubuyblues services")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Ubuyblues Group' refers to a group of companies consisting of Ubuyblues and all its subsidiaries and affiliates")} .</motion.li>
                                <motion.li  className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'The applicable laws' refer to any privacy law, personal data protection law, regulation, treaty, rule, ordinance, license, restriction, judicial or administrative order, law or public law, or any other declaration having legal effect in the State of Kuwait")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Data Subject' or 'You' means an identified or identifiable natural person whose personal data is processed through this website or Ubuyblues services")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Personal data' refers to any information related to the data subject who can be identified, directly or indirectly, particularly by reference to an identifier such as a name, identification number, location data, online identifier, or one or more factors specific to the physical, physiological, genetic, mental, economic, cultural, or social identity of the data subject")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Privacy notice' means this set of terms and conditions that govern the processing of personal data")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Processing' means any operation or set of operations performed on personal data or sets of personal data, whether by automated means or not, such as collection, recording, organization, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination, or otherwise making available, alignment or combination, restriction, erasure, or destruction")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'Website' refers to the electronic website, whose main page is identified by an address, and any online products and services offered by Ubuyblues or call centers indicating this privacy notice")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'It' refers to the International Asfour company for wholesale and retail trade")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("'It' refers to the products and services offered by Ubuyblues online on this website, or the services and call centers that are referenced in this privacy notice")} .</motion.li>
                            </ul>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What personal data do we collect ?")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We collect your personal data to provide and continually improve the services of ubuyblues. We gather various types of personal data")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The personal data provided by the data subject")}</motion.h2>
                            <ul>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("To provide a seamless customer experience, we receive and store your personal data related to the services of ubuyblues, including, but not limited to")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The name, address, and phone numbers")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Payment information")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("age")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("personal description, and photographic image in your profile")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Identity-related information and documents, including civil ID numbers, national ID, and driver's license")} .</motion.li>
                            </ul>
                            <motion.p className="fw-bold mb-4 h5 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We automatically collect and store certain types of personal data about your use of ubuyblues services. We use 'cookies' and other unique identifiers, obtaining specific types of personal data when your web browser or device accesses ubuyblues services. We may collect automatic personal data from, including but not limited to")}</motion.p>
                            <ul>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The Internet Protocol (IP) address used to connect your computer to the internet")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Login information, email address, and password")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The location of your device or computer")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Device metrics such as when the device is in use, application usage, connection data, any errors or failure conditions, version, and timezone settings")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Date of purchase")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Information from other sources")} .</motion.li>
                            </ul>
                            <motion.p className="fw-bold mb-4 h5 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We may receive personal data about you from third-party sources, including ubuyblues and affiliates, such as delivery and address information updated by our transportation companies, which we use to correct our records and facilitate the next purchase delivery. However, we are not responsible for the privacy practices of third-party sites that we do not own, operate, or control. We may collect personal data from other sources, including but not limited to")}</motion.p>
                            <ul>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Delivery information and updated address from third parties")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Search results and links, including paid listings")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Third-party applications or websites that allow us to collect, share, and/or use your personal data")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Third-party sources providing marketing or demographic information about you to enhance our ability to tailor our content and provide ubuyblues services that we believe may interest you")} .</motion.li>
                            </ul>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The purposes for which we use your personal data")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("ubuyblues uses your personal data to operate, provide, develop, and improve the services of the ubuyblues website and application, including but not limited to")} :</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Purchasing, delivery, and promotion")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("ubuyblues uses your personal data to receive and process orders, provide products and services, process payments, and communicate with you regarding orders, products, services, and promotional offers from ubuyblues")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Providing error detection and correction features and improving the services of ubuyblues")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("ubuyblues uses your personal data to provide operational functions, analyze performance, troubleshoot errors, and enhance the usability and effectiveness of ubuyblues services")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Recommendations and customization")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("ubuyblues uses your personal data to recommend products and services that may interest you, identify your preferences, and personalize your experience with ubuyblues")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Compliance with legal obligations")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In some cases, ubuyblues collects your personal data and uses it to comply with applicable laws")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Communication")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Ubuyblues utilizes your personal data to communicate with you regarding application services through various channels (e.g., phone and email) .")}</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Advertisements")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("ubuyblues uses your personal data to display interest-based advertisements for features, products, and services that may be of interest to you. ubuyblues does not use personally identifiable information to display interest-based ads")} .</motion.p>
                            <motion.h5 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Preventing fraud and credit risks")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("ubuyblues uses your personal data to prevent, detect, and investigate fraud and misuse in order to protect the security of ubuyblues and its customers. ubuyblues may also use scoring methods to assess and manage risks")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Disclosure and sharing of your personal data")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We may share your personal data within ubuyblues to provide you access to the services of the website and the application. ubuyblues may market website and application services to you as a result of such sharing unless you explicitly unsubscribe")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Data subject rights")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("When we process your personal data, you have several rights regarding how the personal data is processed, and you can exercise these rights at any time. We have provided an overview of those rights below along with what it entails for you. You can exercise your rights by submitting a data subject rights request form available on this website")} .</motion.p>
                            <motion.h5 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right to access information")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to obtain clear, transparent, and easily understandable information about how we use your personal data")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right of access")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to obtain a copy of the personal data we hold about you and to verify that we process it legally in accordance with applicable laws")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right to rectification")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to correct any incomplete or inaccurate personal data we hold about you. We may need to verify the accuracy of any new personal data you provide us")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right to erasure")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to request the deletion or removal of personal data when there is no compelling reason for us to continue processing it. However, we may not always be able to comply with a deletion request for specific legal reasons, which will be notified to you, if applicable, at the time of your request")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right to object")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In case of non-compliance with this privacy notice or applicable laws for the website and application, you have the right to object to certain types of processing, including processing for direct marketing purposes (e.g., receiving emails from us to notify you or contact you with various potential opportunities)")} .</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right to restrict data processing")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to restrict the processing of your personal data in the following scenarios :")}</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("If you want us to verify the accuracy of personal data")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("When our use of the data is unlawful, but you do not want us to erase it")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Your objection to our processing of your personal data, but we need to verify whether we have legitimate grounds to continue using it")}</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Right to Data Portability")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We will provide you, or a third party of your choice, with your personal data in a structured, commonly used, and machine-readable format. This means it can be transferred, copied, or electronically transmitted under certain circumstances")}</motion.p>
                            <motion.h6 className="fw-bold mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The right to withdraw consent")}</motion.h6>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Your consent to the privacy policy below is the legal basis for Ubuyblues to process your personal data. However, you have the right to withdraw your consent at any time. It is important to note that withdrawing consent does not affect the legality of processing your personal data prior to the successful withdrawal. You can withdraw your consent for the processing of your personal data at any time by contacting us at")} <a href="mailto:info@ubuyblues.com">info@ubuyblues.com</a></motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Rights Related to Automated Decision Making and Profiling")} .</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to lodge a complaint with the relevant data protection authority if you believe that the processing of your personal data violates any of your rights or applicable legal provisions")} :</motion.p>
                            <ul>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Express your opinion")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Obtain an explanation of the decision reached after an assessment")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The right to lodge a complaint with the relevant data protection authority")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have the right to file a complaint with the appropriate data protection authority if you believe that the processing of your personal data violates any of your rights or the provisions of applicable laws")} .</motion.li>
                            </ul>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Excessive or unreasonable request fees")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You will not be required to pay fees to access your personal data or exercise any of the other rights. However, we may impose a reasonable fee if we believe your access request is unfounded or excessive. Instead, we may refuse to comply with the request in such circumstances")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Response times for data subject requests")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We aim to respond to all lawful requests within 30 days. Sometimes, it may take longer if your request is particularly complex or if you have made several requests. In such cases, we will notify you and keep you updated on the progress")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What we may need from you")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We may need to request specific information from you to help us confirm your identity and ensure your right to access personal data (or exercise any of your other rights). This is a security measure to ensure that personal data is not disclosed to anyone who does not have the right to access it. We may also contact you to request further information regarding your request to expedite our response. If you wish to exercise any of the rights outlined above, please contact us at")} <a href="mailto:info@ubuyblues.com">info@ubuyblues.com</a>.</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Personal data of children")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We do not knowingly request or collect personal data from children. If you share any personal data for a child, you acknowledge and warrant that you have the authority to do so and permit Ubuyblues to use the personal data in accordance with the privacy notice")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The period for retaining your personal data")}</motion.h2>
                            <ul>
                                <motion.li className="mb-4">{t("Your personal data is retained in accordance with applicable laws for a period not exceeding what is required for the purpose for which it was collected or as required by applicable laws")} .</motion.li>
                                <motion.li className="mb-4">{t("Ubuyblues retains your personal data wherever it has a legitimate interest, for the performance of a contract, where there is a vital interest to the data subject or another natural person, or for the execution of a task carried out in the public interest or in the exercise of official authority. The data may also be retained to fulfill legal or accounting requirements, or other regulatory reporting requirements, or with your consent. Afterwards, Ubuyblues either deletes or anonymizes the data, making it untraceable to you. However, Ubuyblues may continue to retain your personal data if it believes it is necessary to prevent fraud or future misuse, to enable Ubuyblues to exercise its legal rights, and/or to defend against legal claims, or if required by applicable laws or for other legitimate purposes. Ubuyblues may continue to retain your personal data in an anonymized form for analytical and research purposes")} .</motion.li>
                            </ul>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How we protect your personal data ?")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In an effort to protect your personal data from unauthorized access, disclosure, loss, alteration, or misuse, we employ security practices and measures, based on our discretion, in accordance with applicable laws or international standards")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Such as ISO/IEC 27001:2013. We design our systems with consideration for security and privacy. We adhere to standard security measures and continuously update our systems to protect your personal data from any breaches or virus exposure. We use various methods to safeguard personal data as outlined below")} :</motion.p>
                            <ul>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Physical measures include locked file cabinets, restricted access to offices, and alarm systems")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Technological tools such as password encryption and encryption using best practices in this field in general")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Regulatory controls, confidentiality agreements, restricted access on a need-to-know basis, employee training, and security clearances")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Online security is enhanced through the integration of measures such as encryption tools and authentication to protect your personal data from unauthorized use. Firewalls are used to protect our servers and network from unauthorized user access and tampering with files and other personal data we store. Additionally, we conduct regular malware scans to prevent data breaches")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Your personal data is contained behind secured networks and can only be accessed by a limited number of individuals who have special access rights to these systems and are required to keep the personal data confidential. In addition, all sensitive personal data and credit card information you provide is encrypted via Secure Socket Layer (SSL) technology")}</motion.li>
                            </ul>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Changing the Purpose")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We will use your personal data for the purposes outlined in this privacy policy only, unless we find a justifiable reason to use it for another reason, and that reason is compatible with the original purpose")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("If we need to use your personal data for an unrelated purpose, we will inform you and explain the legal basis that allows us to do so. If you would like an explanation of how the processing for the new purpose is compatible with the original purpose, please contact the Data Protection Officer using the contact details provided in this privacy notice")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Aggregated or Pre-classified Data")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Ubuyblues may also collect and/or generate anonymized and aggregated information from your use of Ubuyblues services. Anonymous or aggregated information is not considered personal data, as we are unable to identify you using any available means from that anonymized or aggregated information. The anonymous and aggregated information is used for various tasks, including assisting us in identifying and addressing any errors, improving the performance of Ubuyblues services, and may be used in various ways such as internal analysis, analytics, and research. Ubuyblues may share this information with third parties for purposes related to them or their interests in an anonymized or aggregated form designed to prevent anyone from identifying you")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Consent, Compensation, and Liability")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In accordance with the Privacy Notice, you hereby grant Ubuyblues the right to process your personal data, internally or with third parties, for the purposes outlined in this notice. You acknowledge that you provided your personal data voluntarily and that this personal data is true, accurate, complete, and up-to-date")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You agree to defend Ubuyblues and its contributors, officials, directors, employees, and indemnify and protect them from any and all claims, liabilities, damages, losses, or expenses (including, but not limited to, settlement amounts, reasonable legal fees, and personal expenses) arising out of or related to any form of your access to or use of this website")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Ubuyblues and its directors and employees shall not be liable in any form for any direct, indirect, incidental, consequential, or punitive damages (including, but not limited to, loss of profits, business interruption, and loss of programs on your information system) arising out of or related to")} :</motion.p>
                            <ol>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The use or access to, or inability to use, the information or branching links available on this website or Ubuyblues's services or any vendor services")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Your provision of any information, including your personal data")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Any failure, delay, error, interruptions, or inaccuracies directly or indirectly resulting from any cause, including but not limited to unauthorized access or misuse of personal data by any third party, network service failures, or the operation of this website or any solution operating this website")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Actions or negligence of Ubuyblues or any of its affiliated external service providers, agents, or employees")} .</motion.li>
                            </ol>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Ubuyblues disclaims and excludes to the fullest extent permitted by applicable laws all warranties and representations, whether express, implied, or statutory, regarding this website or the result of your use of this website or Ubuyblues's services, or regarding the accuracy, currency, or completeness of the information provided by Ubuyblues, including, for example, implied warranties of fitness for a particular purpose and non-infringement of patent, trademark, or any other intellectual property right. All contents of this website, including, for example, all content and information and links therein, are provided 'as is' with no warranty that they will be uninterrupted or error-free. This disclaimer applies to all causes of action, whether based on contract, warranty, tort, or any other legal theories")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Membership Terms for Adding Your E-commerce Store and Opening an Account")}</motion.h2>
                            <ol>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You must be 18 years of age or older according to laws and regulations")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The store's activity must be within permissible commercial fields, and any deviation will result in the rejection of the application")}</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You must register with Ubuyblues to use and benefit from the service by contacting the Ubuyblues team via email at info@ubuyblues.com for agreement and setup. Ubuyblues reserves the right to reject any request to create an account or add your e-commerce store. Furthermore, Ubuyblues reserves the right to terminate the 'Add Your E-commerce Store' service or any account for any violation within the website's policy without prior notice and at any time")} .</motion.li>
                            </ol>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Customer Code of Conduct Policy")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("At Ubuyblues, customer satisfaction is our top priority, and we strive to resolve all customer issues in a professional and friendly manner. However, we will not tolerate any unacceptable or unreasonable behavior towards our customer service team members")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Unacceptable behavior towards Ubuyblues's customer service employees may include, for example")} :</motion.p>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Submitting repetitive or consistently malicious complaints, despite the matter being fully addressed; similarly, ongoing repetition of complaints despite reasonable and fair solutions provided according to our policies")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Demanding or expecting employees to violate the company's applicable policy guidelines")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("A high number of complaints compared to the total purchase value history")} .</motion.li>
                            </ul>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("For such behavior, complainants may be notified formally with the following")} :</motion.p>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Their language is considered offensive, abusive, threatening, and entirely unacceptable")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("They must refrain from using such language, abuse, and threats")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("There will be no further exchange of correspondence on this matter if they continue this behavior")} .</motion.li>
                            </ul>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Ubuyblues reserves the right to refuse customer requests in the future without further notice")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Complaint Escalation Process")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("This process strictly applies to customer service issues. For separate legal issues such as copyright rights")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Contact Us > Submit a Ticket > Select Warranty and Return > Submit Formal Complaint")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We will respond to all complaints within 24 hours, excluding weekends and official holidays")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Intellectual property rights")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("This website and all its contents, including but not limited to all texts, graphics, HTML code, all product names, trade names, service names, domain names, and trademark fonts or logos in any form or text, are materials protected by copyright and may not be printed, copied, published, reproduced, or used (including images of faces) or distributed in whole or in part without the prior written consent of Ubuyblues")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Changes to the Privacy Notice")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We may update this privacy notice from time to time in response to legal, technical, contractual, regulatory, or business developments. When we update our privacy notice, we will take appropriate steps to notify you, in accordance with the significance of the changes we make. Your continued use of this website constitutes acceptance of these changes. We will obtain your consent to any material changes to the privacy notice where and to the extent required by applicable laws")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You can find out the last update date of the corresponding privacy notice by checking the 'Last Modified' date displayed at the end of the corresponding privacy notice")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Payment")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We accept Visa, MasterCard, and KNET cards, as well as any other payment methods that may be clearly announced on the website from time to time. Payments will be deducted from your account and released before your order is sent. You confirm that you are the owner of the credit or debit card used, or that the owner of the credit or debit card has specifically authorized you to use it. All credit and debit cardholders are subject to data validation and authentication processes by the card issuer")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We take reasonable care to maintain the security of the website, and all financial transactions on credit or debit cards on this site are processed through secure electronic payment gateways where card data is encrypted in a secure host environment. We securely store your credit or debit card information on our systems, and this data is fully encrypted and used solely to process transactions for the cards you have created")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("We also give a reasonable amount of care and as much as possible to maintain the security of data related to purchase orders and payments. Accordingly, in the absence of negligence on our part, we cannot be held responsible for any loss you may incur if another party obtains any data, you provide when accessing the website or making a purchase through it without permission")} .</motion.p>
                            <motion.h3 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("TABBY")}</motion.h3>
                            <motion.h4 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What is Tabby service ?")}</motion.h4>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("It is a service provided by UbuyBlues in collaboration with Tabby, which allows the customer to purchase products through the UbuyBlues website or app and pay for them in monthly installments")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Advantages")}</motion.h5>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("4 monthly installments")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Immediate approval")} .</motion.li>
                            </ul>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Terms and conditions")}</motion.h5>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The Tabby payment service is available on the UbuyBlues website")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Payment through Tabby service is available on all products")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Products purchased through the Tabby service cannot be returned")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("UbuyBlues' policy applies to exchanges and returns")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Service fees will apply when paying with Tabby")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("UbuyBlues is not responsible for any issues related to the customer's account or payment in the Tabby app. For technical issues with the Tabby app or website, please contact Tabby customer service at +96522270163 or email: help@tabby.ai")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("A good payment history with Tabby can improve your chances of getting approved for more purchases, in addition to the duration you have been using Tabby for shopping")} .</motion.li>
                            </ul>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The transaction may be rejected for one of the following reasons")}</motion.h5>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Not paying the payments on time. Pay it off and try again")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You have a negative balance")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The total amount in the cart may have exceeded the limit, please removed some items and try again")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Uploading an incorrect or unclear ID card")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Service fees will apply when paying with Tabby")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In case of non-payment on time, a fee of 1.25 Kuwaiti Dinars will be charged after the due date. If you do not make the payment within 14 days, an additional fee of 2.5 Kuwaiti Dinars will be applied. In case of a delay of 28 days, an additional fee of 2.5 Kuwaiti Dinars will be added")} .</motion.li>
                            </ul>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Frequently Asked Questions")}</motion.h5>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What are the requirements for using Tabby ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Tabby is available to all citizens and residents. We only need your mobile phone number and a valid payment method")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What is the minimum and maximum purchase amount using the Tabby service ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The minimum purchase is 20 Kuwaiti Dinars, and the maximum is 500 Kuwaiti Dinars")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In case the invoice amount is more than 500 Kuwaiti Dinars, the customer can pay the remaining amount as follows")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The remaining amount will be added to the first installment payment. For example")} :</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("If the invoice amount is 700 Kuwaiti Dinars and the customer's approval from Tabby is 500 Kuwaiti Dinars. The client will pay the remaining amount of 200 Kuwaiti Dinars with the first installment of 125 Kuwaiti Dinars, thus the total of the first payment will be 325 Kuwaiti Dinars, the second payment will be 125 Kuwaiti Dinars, the third payment will be 125 Kuwaiti Dinars, and the fourth payment will be 125 Kuwaiti Dinars")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Is there a limit to how much I can spend on a single purchase with Tabby ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The maximum for a single purchase is 700 Kuwaiti Dinars. The decision on the limit also depends on")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Your previous commitment to pay Tabi installments")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Your remaining balance and unpaid payments")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The size of the shopping cart")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Other factors for approving consent cannot be disclosed for security reasons")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How do I pay ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The easiest and fastest way to make and review payments is through the Tabby app. When using any card while shopping with Tabby, payments will not be automatically processed, and you will need to log into your Tabby account to make the payment. You will receive emails and text messages to remind you of the due dates for upcoming payments. In case you wish to make an early payment, log in online, or download the app, select the payment you want to make, and choose 'Payment Options'. There are no fees when you make early payments")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Follow the steps below to complete the payment process")} :</motion.p>
                            <ol>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Log in to the Tabby app or Tabby online")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Click on the 'My Payments' option from the menu")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Choose the order you want to pay for or pay all remaining installments")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Follow the displayed steps to complete the payment and ensure that the correct payment details are used when making the payment to avoid any mistakes")} .</motion.li>
                            </ol>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What are the payment methods on the Tabby website or app ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Tabby accepts Apple Pay and all bank and credit cards, such as MasterCard and Visa")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Are you having trouble paying for your order with Tabby ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Tabby does not approve all purchase requests; Tabby is committed to promoting responsible spending habits. We understand that receiving a purchase request rejection is frustrating, especially since previous transactions from you have been accepted. But Tabby relies on several factors to determine whether the request is accepted or rejected, while the purchase limit is determined by the store you are shopping from. We would like to point out that our customer service team cannot change these automated results")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How do you increase the chances of getting the request approved ?")}</motion.h5>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Commitment to making payments on time, in addition to your usage period with Tabby")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("If you have a negative balance or unpaid payments, settle them")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The basket amount might be large, try to reduce the amount")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Make sure you have only one Tabby account")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("With every purchase using Tabby, we make new and different decisions. If the purchase was previously rejected, it does not mean that all future purchase requests will be rejected. You can always try to pay with Tabby again")} .</motion.li>
                            </ul>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How does Tabby work ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Tabby allows you to split your purchases into 4 monthly installments without interest or fees. You can make a purchase by following these steps")} .</motion.p>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Step one: Choose Tabby as your payment method")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Step two: Link any bank card")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Step three: Complete only the first payment, and Tabby will remind you before the due dates of the other payments")} .</motion.li>
                            </ul>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Can I pay before the due date ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Yes! If you wish to pay the outstanding balance for your purchase in installments early, simply log in to Tabby, go to the order page, and select early payment")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Can I change the card used for payment ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You can view all amounts, make payments, and manage your personal account by logging in online or using the Tabby app")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Follow the steps below to change the card")} :</motion.p>
                            <ol>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Log in to the Tabby app")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Click on the 'Installment Request' option")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Choose to change the card")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Enter the details of your new card")} .</motion.li>
                            </ol>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How do I know when I need to pay ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("You will receive regular reminders before any due payments to avoid missing them")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The payment is due, but I haven't received my products!")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Please inform Tabi that you have not received the order. Once reported, Tabi will adjust your account to ensure that you do not need to make any payment until the issue is resolved. If you have not received the products, please do the following, and then we will adjust your account to ensure that you do not need to make any payment until the issue is resolved")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Contact UbuyBlues if you don't find any information about the shipment or if there is a delay in the delivery date")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Let us know!")}</motion.h5>
                            <ol>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Log in to the Tabby app")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Click on 'My Payments'")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Choose the request that has the issue")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Click on 'Need Help'")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Choose 'I have a payment due, and I haven't received my order yet!' And then contact us")} .</motion.li>
                            </ol>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("What happens if I don't pay on time ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Delay in payment. In case of late payment, you are obliged to pay an additional fee from the date of default")} .</motion.p>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How can I get a refund ?")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Refunds are processed according to UbuyBlues' return and cancellation policy. The amounts are processed once UbuyBlues registers the return or cancellation request, and Tabby begins the process of refunding you. Here’s what you can expect from the recovery process with Tabby")} :</motion.p>
                            <ul>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In the case where the refunded amount is less than the remaining amounts, the remaining amounts will be adjusted accordingly")} .</motion.li>
                                <motion.li className="mb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("In the case where the refunded amount is greater than the remaining amounts, the remaining payments will be canceled, and the remaining amount will be refunded accordingly")} .</motion.li>
                            </ul>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("How long does it take to process a refund ?")}</motion.h5>
                            <motion.p className="mb-4">{t("The amount will be refunded to the card used for the payment, and it will take 2-5 business days. But the process may take longer depending on your bank")} :</motion.p>
                            <motion.h4 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("BINANCE")}</motion.h4>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Using Binance on UbuyBlues")}</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("checking out with Binance on UbuyBlues is easy and secure. Refunds for purchases made via Binance can be processed directly to Binance")} .</motion.p>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("The pay with Binance option is only available on desktop currently")} .</motion.p>
                            <ol>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("During the Payment section of checkout select, the Binance option then proceed to pay with Binance")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Begin payment and select your wallet Binance")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Select your USDT currency")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Once you’re ready to pay either")} .</motion.li>
                                <motion.li className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("scan the QR code within your mobile Binance app or Select Pay in Wallet")} .</motion.li>
                            </ol>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("All returns follow our return policy")}</motion.h5>
                            <motion.h5 className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Note")} :</motion.h5>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("When using Binance as your payment method, once you have clicked the “Pay with Binance” button, you will have only 15 minutes to complete your payment. If you are unable to complete your payment, you will have two options: You can try again later to place a new order or you can change your payment method later from Order History in My Account")} .</motion.p>
                            <motion.h2 className="fw-bold mb-4 h4 border-bottom border-2 w-fit pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("Contact us")}</motion.h2>
                            <motion.p className="mb-4" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>{t("If you have any comments or inquiries regarding our terms or privacy policy, you can contact us by sending an email or calling customer service at the following address")} .</motion.p>
                            <motion.a href="mailto:info@ubuyblues.com" className="text-white border-bottom pb-2" initial={getInitialStateForElementBeforeAnimation()} whileInView={getAnimationSettings}>info@ubuyblues.com</motion.a>
                        </div>
                    </div>
                </div>
                <Footer />
            </>}
            {isLoadingPage && !errorMsgOnLoadingThePage && <LoaderPage />}
            {errorMsgOnLoadingThePage && <ErrorOnLoadingThePage errorMsg={errorMsgOnLoadingThePage} />}
        </div>
    );
}